version: '3'
services:
    service_postgres:
      image: postgres
      container_name: ctr_postgres
      restart: "always"
      ports:
        - "54320:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=sales_dm
      volumes:
        - ./data:/data
        - ./sql:/sql
