--Total Number of Orders () shipped to a specific STATE in a given year

DROP VIEW IF EXISTS DM.REPORT_NUMBEROFORDERS_SHIPPED_BY_STATE;

CREATE VIEW DM.REPORT_NUMBEROFORDERS_SHIPPED_BY_STATE AS
SELECT
	STATE,
	YEAR,
	COUNT(ORDER_ID) AS NUMBER_OF_ORDERS
FROM
	(
	SELECT
		ORDER_ID,
		YEAR,
		STATE
	FROM
		DM.FACTORDERS O
	LEFT JOIN DM.DIMADDRESS_HISTORY AH ON
		AH.ADDRESS_ID = O.ADDRESS_ID
) TBL
GROUP BY
	STATE,
	YEAR;

SELECT * FROM DM.REPORT_NUMBEROFORDERS_SHIPPED_BY_STATE;