--List customers current address

DROP VIEW IF EXISTS DM.REPORT_CUSTOMERS_LATEST_ADDRESS;

CREATE VIEW DM.REPORT_CUSTOMERS_LATEST_ADDRESS AS
SELECT
	C.*,
	AH.STREET_NUMBER,
	AH.CITY,
	AH.POSTAL_CODE,
	AH.STATE
FROM
	DM.DIMCUSTOMERS C
JOIN DM.DIMADDRESS_HISTORY AH ON
	AH.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
	AH.END_DATE IS NULL
ORDER BY
	CUSTOMER_ID
;


SELECT * FROM DM.REPORT_CUSTOMERS_LATEST_ADDRESS ORDER BY FIRST_NAME, LAST_NAME;