--Summary Report that show all orders and there order status report

DROP VIEW IF EXISTS DM.REPORT_SUMMARY_OF_ORDERS_WITH_ORDER_STATUS;

CREATE VIEW DM.REPORT_SUMMARY_OF_ORDERS_WITH_ORDER_STATUS AS
WITH CTE AS
(
SELECT
--	COUNT(F.ORDER_ID) AS NUMBEROFORDERS,
	SUM(F.AMOUNT) AS ORDERTOTALAMOUNT,
	F.YEAR,
	O.ORDER_STATUS
FROM
	DM.FACTORDERS F
JOIN DM.DIMORDERS O ON
	F.ORDER_ID = O.ORDER_ID
GROUP BY
	YEAR,
	ORDER_STATUS
)
SELECT
	'YEARLY_TOTAL' AS REPORTTITLE,
--	NUMBEROFORDERS,
	ORDERTOTALAMOUNT,
	YEAR,
	ORDER_STATUS
FROM
	CTE
UNION
SELECT
	'GRAND_TOTAL' AS REPORTTITLE,
--	SUM(NUMBEROFORDERS),
	SUM(ORDERTOTALAMOUNT),
	COUNT(YEAR) AS YEAR,
	ORDER_STATUS
FROM
	CTE
GROUP BY
	ORDER_STATUS
ORDER BY
	REPORTTITLE DESC,
	YEAR,
	ORDER_STATUS
;

SELECT * FROM DM.REPORT_SUMMARY_OF_ORDERS_WITH_ORDER_STATUS ORDER BY REPORTTITLE DESC, YEAR, ORDER_STATUS;