-- QUARTERLY SALES REPORT AT PRODUCT LEVEL
-- PRODUCT_NAME, SUM(AMOUNT), YEAR ,Q1,Q2,Q3,Q4

DROP VIEW IF EXISTS DM.REPORT_QUARTERLY_SALES_SUMMARY_BY_PRODUCTS;

CREATE VIEW DM.REPORT_QUARTERLY_SALES_SUMMARY_BY_PRODUCTS AS
SELECT
	PRODUCT_NAME,
	YEAR,
	MAX(Q1) AS Q1_AMOUNT,
	MAX(Q2) AS Q2_AMOUNT,
	MAX(Q3) AS Q3_AMOUNT,
	MAX(Q4) AS Q4_AMOUNT,
	SUM(YEARLY_AMOUNT) AS YEARLY_AMOUNT
FROM
	(
	SELECT
	PRODUCT_NAME,
		FOD.YEAR,
		SUM(CASE WHEN QUARTER = 1 THEN FOD.AMOUNT ELSE 0 END) AS Q1,
		SUM(CASE WHEN QUARTER = 2 THEN FOD.AMOUNT ELSE 0 END) AS Q2,
		SUM(CASE WHEN QUARTER = 3 THEN FOD.AMOUNT ELSE 0 END) AS Q3,
		SUM(CASE WHEN QUARTER = 4 THEN FOD.AMOUNT ELSE 0 END) AS Q4,
		SUM(FOD.AMOUNT) AS YEARLY_AMOUNT
	FROM
		DM.FACTORDERDETAIL FOD
	JOIN DM.DIMORDERDETAILS OD ON OD.ORDER_DETAIL_ID =FOD.ORDER_DETAIL_ID
	GROUP BY
		OD.PRODUCT_NAME,
		FOD.YEAR,
		FOD.QUARTER,
		FOD.QUARTAL
) TBL
GROUP BY
	PRODUCT_NAME,
	YEAR
ORDER BY
	PRODUCT_NAME,
	YEAR;

SELECT * FROM DM.REPORT_QUARTERLY_SALES_SUMMARY_BY_PRODUCTS ORDER BY PRODUCT_NAME,YEAR;