-- QUARTERLY SALES REPORT AT CUSTOMER LEVEL
-- CUSTOMER_ID, SUM(AMOUNT), YEAR, Q

DROP VIEW IF EXISTS DM.REPORT_QUARTERLY_SALES_BY_CUSTOMERS;

CREATE VIEW DM.REPORT_QUARTERLY_SALES_BY_CUSTOMERS AS 
SELECT
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME,
	FO.YEAR,
	FO.QUARTER,
	FO.QUARTAL,
	SUM(FO.AMOUNT) AS QUARTERLY_AMOUNT
FROM
	DM.FACTORDERS FO
JOIN DM.DIMCUSTOMERS C ON
	FO.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME,
	FO.YEAR,
	FO.QUARTER,
	FO.QUARTAL
ORDER BY
	C.CUSTOMER_ID,
	FO.YEAR,
	FO.QUARTER;

SELECT * FROM DM.REPORT_QUARTERLY_SALES_BY_CUSTOMERS ORDER BY CUSTOMER_ID,YEAR,QUARTER;


