-- 03_ingest_csv_legacy_data.sql

DROP TABLE IF EXISTS LEGACY.LEGACYORDERS;

CREATE TABLE LEGACY.LEGACYORDERS (
    ORDER_ID TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    DATE_OF_BIRTH TEXT NOT NULL,
    PHONE TEXT NULL,
    EMAIL TEXT NOT NULL,
    STREET TEXT NULL,
    CITY TEXT NULL,
    POSTAL_CODE TEXT NULL,
    STATE TEXT NULL,
    ORDER_DATE TEXT NOT NULL,
    PAYMENT_TYPE TEXT NOT NULL,
    PRODUCT_NAME TEXT NOT NULL,
    PRICE TEXT NOT NULL,
    QUANTITY TEXT NOT NULL,
    ORDER_TOTAL TEXT NOT NULL
);

-- Load legacy csv data
COPY LEGACY.LEGACYORDERS FROM '/data/historical_orders_tumbleweed_capital.csv' CSV HEADER;

