-- 04_create_dimensional_schemas.sql

-- Create dimensional tables

DROP TABLE IF EXISTS DIMPAYMENTMETHOD;

CREATE TABLE DM.DIMPAYMENTMETHOD (
    PAYMENT_METHOD_ID SMALLSERIAL PRIMARY KEY,
    PAYMENT_TYPE TEXT NOT NULL
);

DROP TABLE IF EXISTS DIMCUSTOMERIDLOOKUP;

CREATE TABLE DM.DIMCUSTOMERIDLOOKUP (
    CUSTOMER_ID UUID DEFAULT GEN_RANDOM_UUID (),
    EMAIL TEXT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

DROP TABLE IF EXISTS DIMCUSTOMERS;

CREATE TABLE DM.DIMCUSTOMERS (
    CUSTOMER_ID UUID DEFAULT GEN_RANDOM_UUID (),
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

DROP TABLE IF EXISTS DIMORDERS;

CREATE TABLE DM.DIMORDERS (
    ORDER_ID INTEGER NOT NULL,
    CUSTOMER_ID UUID NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS TEXT NULL,
    PAYMENT_METHOD_ID TEXT NULL,
    COMMENTS TEXT NULL,
    PRIMARY KEY (ORDER_ID)
);

DROP TABLE IF EXISTS DIMORDERDETAILS;

CREATE TABLE DM.DIMORDERDETAILS (
    ORDER_DETAIL_ID UUID DEFAULT GEN_RANDOM_UUID (),
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_NAME TEXT NULL,
    PRICE NUMERIC(10,2) NOT NULL,
    QUANTITY SMALLINT NOT NULL,
    COMMENTS TEXT NULL,
    PRIMARY KEY (ORDER_DETAIL_ID)
);

DROP TABLE IF EXISTS DIMADDRESS_HISTORY;

CREATE TABLE DM.DIMADDRESS_HISTORY (
    ADDRESS_ID UUID DEFAULT GEN_RANDOM_UUID (),
    CUSTOMER_ID UUID,
    STREET_NUMBER TEXT NOT NULL,
    CITY TEXT NOT NULL,
    POSTAL_CODE TEXT NOT NULL,
    STATE TEXT NOT NULL,
    START_DATE DATE NULL,
    END_DATE DATE NULL,
    LATESTROW INTEGER NULL,
    PRIMARY KEY (ADDRESS_ID)
);
