-- 05_load_dimension_schemas.sql

--DIMPAYMENTMETHOD
INSERT INTO DM.DIMPAYMENTMETHOD(PAYMENT_TYPE)
SELECT DISTINCT PAYMENT_TYPE FROM LEGACY.LEGACYORDERS
WHERE PAYMENT_TYPE NOT IN (SELECT PAYMENT_TYPE FROM DM.DIMPAYMENTMETHOD);

--DIMCUSTOMERIDLOOKUP
INSERT INTO DM.DIMCUSTOMERIDLOOKUP(EMAIL)
SELECT DISTINCT EMAIL FROM LEGACY.LEGACYORDERS ORDER BY EMAIL;

--DIMCUSTOMERS
INSERT INTO DM.DIMCUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,PHONE,EMAIL)
SELECT DISTINCT
CL.CUSTOMER_ID, 
C.FIRST_NAME,
C.LAST_NAME,
TO_DATE(C.DATE_OF_BIRTH, 'MM/DD/YY') AS DATE_OF_BIRTH,
C.PHONE,
C.EMAIL
FROM LEGACY.LEGACYORDERS C 
JOIN DM.DIMCUSTOMERIDLOOKUP CL ON  CL.EMAIL = C.EMAIL;

--DIMORDERS
INSERT INTO DM.DIMORDERS(ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,PAYMENT_METHOD_ID,COMMENTS)
SELECT DISTINCT
CAST(C.ORDER_ID AS INTEGER) AS ORDER_ID,
CL.CUSTOMER_ID, 
TO_DATE(C.ORDER_DATE, 'MM/DD/YY') AS ORDER_DATE,
'COMPLETED' AS ORDER_STATUS,
PT.PAYMENT_METHOD_ID,
'HISTORIC LOAD' AS COMMENTS
FROM LEGACY.LEGACYORDERS C 
JOIN DM.DIMCUSTOMERIDLOOKUP CL ON  CL.EMAIL = C.EMAIL
LEFT JOIN DM.DIMPAYMENTMETHOD PT ON PT.PAYMENT_TYPE = C.PAYMENT_TYPE;

--DIMORDERDETAILS
-- INSERT INTO DM.DIMORDERDETAILS(ORDER_ID,PRODUCT_NAME,PRICE,QUANTITY,AMOUNT,COMMENTS)
INSERT INTO DM.DIMORDERDETAILS(ORDER_ID,PRODUCT_NAME,PRICE,QUANTITY,COMMENTS)
SELECT DISTINCT
CAST(ORDER_ID AS INTEGER) AS ORDER_ID,
PRODUCT_NAME,
CAST(PRICE AS NUMERIC(10,2)) AS PRICE,
CAST(QUANTITY AS SMALLINT) AS QUANTITY,
--CAST(PRICE AS NUMERIC(10,2)) * CAST(QUANTITY AS SMALLINT) AS AMOUNT,
'HISTORIC LOAD' AS COMMENTS
FROM LEGACY.LEGACYORDERS;


--DIMADDRESS_HISTORY
INSERT INTO DM.DIMADDRESS_HISTORY(CUSTOMER_ID,STREET_NUMBER,CITY,POSTAL_CODE,STATE,START_DATE,END_DATE,LATESTROW)
SELECT DISTINCT
CUSTOMER_ID,STREET_NUMBER,CITY,POSTAL_CODE,STATE,START_DATE,
LEAD(START_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS END_DATE,
ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID,STREET_NUMBER,CITY,POSTAL_CODE,STATE ORDER BY START_DATE DESC) AS LATESTROW
FROM
(
SELECT DISTINCT
CL.CUSTOMER_ID,
C.STREET AS STREET_NUMBER,
C.CITY,
C.POSTAL_CODE,
C.STATE,
TO_DATE(C.ORDER_DATE, 'MM/DD/YY') AS START_DATE
FROM LEGACY.LEGACYORDERS C 
JOIN DM.DIMCUSTOMERIDLOOKUP CL ON  CL.EMAIL = C.EMAIL
) AS TBL
ORDER BY CUSTOMER_ID,START_DATE;


--FACTSALES


