-- 06_create_load_dimensional_fact_schemas.sql

DROP VIEW IF EXISTS DM.V_FACTORDERDETAIL;

CREATE VIEW DM.V_FACTORDERDETAIL AS
SELECT 
10000 * EXTRACT(YEAR FROM O.order_date) + 100 * EXTRACT(MONTH FROM O.order_date) + EXTRACT(DAY FROM O.order_date) AS ORDER_DATEKEY,
D."YEAR" as YEAR,
D."MONTH" as MONTH,
D.QUARTER_ACTUAL as QUARTER,
D.QUARTAL,
D.YEARQUARTAL,
D.YEARMONTH,
O.CUSTOMER_ID,AH.ADDRESS_ID,
OD.ORDER_ID,
OD.ORDER_DETAIL_ID,
CAST(OD.PRICE AS NUMERIC(10,2)) * CAST(OD.QUANTITY AS SMALLINT) AS AMOUNT
FROM DM.DIMORDERDETAILS as OD
JOIN DM.DIMORDERS as O ON OD.ORDER_ID=O.ORDER_ID
JOIN DM.DIMDATE AS D ON D.DATEKEY=10000 * EXTRACT(YEAR FROM O.order_date) + 100 * EXTRACT(MONTH FROM O.order_date) + EXTRACT(DAY FROM O.order_date)
LEFT JOIN DM.DIMADDRESS_HISTORY AH ON AH.CUSTOMER_ID = O.CUSTOMER_ID AND O.ORDER_DATE = AH.START_DATE;


-- SELECT * FROM DM.V_FACTORDERDETAIL ORDER BY ORDER_DATEKEY;

DROP VIEW IF EXISTS DM.V_FACTORDERS;

CREATE VIEW DM.V_FACTORDERS AS
SELECT 
ORDER_DATEKEY,
YEAR,
MONTH,
QUARTER,
QUARTAL,
YEARQUARTAL,
YEARMONTH,
CUSTOMER_ID,ADDRESS_ID,
ORDER_ID,
SUM(AMOUNT) AS AMOUNT
FROM DM.V_FACTORDERDETAIL
GROUP BY ORDER_DATEKEY,
YEAR,
MONTH,
QUARTER,
QUARTAL,
YEARQUARTAL,
YEARMONTH,
CUSTOMER_ID,
ADDRESS_ID,
ORDER_ID;

-- SELECT * FROM DM.V_FACTORDERS ORDER BY ORDER_DATEKEY;

-- 07_load_dimensional_fact_schemas.sql

DROP TABLE IF EXISTS DM.FACTORDERDETAIL;
CREATE TABLE DM.FACTORDERDETAIL AS
SELECT * FROM DM.V_FACTORDERDETAIL ORDER BY ORDER_DATEKEY;

-- SELECT * FROM DM.FACTORDERDETAIL ORDER BY ORDER_DATEKEY;

DROP TABLE IF EXISTS DM.FACTORDERS;
CREATE TABLE DM.FACTORDERS AS
SELECT * FROM DM.V_FACTORDERS ORDER BY ORDER_DATEKEY;

-- SELECT * FROM DM.FACTORDERS ORDER BY ORDER_DATEKEY;